name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Nightly build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Init python poetry action
        uses: abatilo/actions-poetry@v2.1.0
      - uses: actions/cache@v1
        id: cache-deps
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: poetry install -E session

      - uses: actions/cache@v1
        with:
          path: .mypy_cache
          key: mypy-${{ matrix.python-version }}
      - uses: actions/cache@v1
        with:
          path: .pytest_cache
          key: pytest-${{ matrix.python-version }}
      - name: Check docs build
        # only run this for the python version used by netlify:
        if: matrix.python-version == 3.8
        run: poetry run make docs-build-ci
      - name: Check that formatting, linting, and tests pass
        run: poetry run make ci
